default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/footy_dev

test:
  <<: *default
  database: db/footy_test

production:
  <<: *default
  database: db/footy_prod
