# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b858cf90e604f1ee6d53699a4d2831ffdb21abfe89536f208b3b3300edaa735f4ec60bddb3e3aac8346de7486b650a900d619869647e0a382c6adcbb3c3646fc

test:
  secret_key_base: 6f1b5a0a6ddb950af091e6a5b5147fe2e9c0a9847674b02175b1524f0a2de3ef67b27ccd9d3f4d7d97397a7baedd279f57b842cf95bf74aae102b2dce5c02342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
